spring:
  datasource:
    url: jdbc:oracle:thin:@172.16.1.162:1521:NEXOS
    username: YMWSM
    password: admin@ymwsm
    driver-class-name: oracle.jdbc.OracleDriver
jwt:
  expiration_time: 3600
  secret: "dainformationparjinseo";