spring:
  datasource:

  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    generate-ddl: true
  security:
    user:
      name: user
      password: 1234

logging:
  level:
    org.hibernate.SQL: debug