spring:
  application:
    name: wos
  profiles:
    active: prod

jwt:
  expiration_time: 3600
  secret: dainformationparkjinseodainformationparkjinseodainformationparkjinseodainformationparkjinseodainformationparkjinseo