spring:
  datasource:
    url: jdbc:oracle:thin:@172.16.1.162:1521:
    username:
    password:
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: create-drop  # none : DB에 TABLE 만들어 놔야 함.
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    generate-ddl: true
  security:
    user:
      name: user
      password: 1234

logging:
  level:
    org.hibernate.SQL: debug